before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
docker:
  image_templates:
    - "thecasualcoder/{{ .ProjectName }}:{{ .Tag }}"
    - "thecasualcoder/{{ .ProjectName }}:v{{ .Major }}"
    - "thecasualcoder/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    - "thecasualcoder/{{ .ProjectName }}:latest"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
