#!/usr/bin/env bash

set -e

echo "Performing app pre boot-up actions"
wget https://api.github.com/users/arunvelsriram -O arunvelsriram.json
wget https://api.github.com/users/dineshba -O dineshba.json
echo "Done"

# take all the arguments and execs them as a command
exec "$@"
